### PR TITLE
Added support for gems on git repositories

### PR DESCRIPTION
**Pull request by dariocravero**
Hey @cyx,

How're you doing?

I've added support for gems on git repositories - ref. #9.

I know this adds a good number of lines to the codebase and the aim is to keep it simple. Anyway, it might be a good starting point if this feature is of interest.

You can now:

`dep add gs --git git://github.com/soveran/gs`

and it will pull `gs` from its git repository.

If you happen to have many gems on one repository, you can also do:

`dep add padrino-performance --git git://github.com/padrino/padrino-framework padrino-performance`

Doing an install will clone the repo in a temporary directory, build and install the gem into your gemset.

Let me know what you think about it :)
Thanks!

### CODE REVIEW

**Comment by cyx** [comment]
Hi, never got the chance to reply -- I thought I did.

Were were thinking of doing a plugin system at the time. For now not ready to add this. Thanks!

**Comment by dariocravero** [comment]
That's fine. Thanks for coming back on this :)

**Comment by scalp42** [comment]
@cyx any chance to revisit this? The huge drawback is the impossibility to install gems from git.

**Comment by scalp42** [comment]
@dariocravero any chance to add support for specifying a branch/tag with a `@` at the end?

**Pull request closed without merging**
